version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    # environment:
    #   - DATABASE_HOSTNAME=postgres
    #   - DATABASE_PORT=5432
    #   - DATABASE_PASSWORD=1234
    #   - DATABASE_NAME=secrets
    #   - DATABASE_USERNAME=postgres
    #   - SECRET_KEY=alkmkdl2940fnewcdcm32ekmlw0wnjkdcl
    #   - ALGORITHM=HS256
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=secrets
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: